// Code generated by counterfeiter. DO NOT EDIT.
package appfakes

import (
	"sync"

	"github.com/vitakras/libinput-gestures/pkg/app"
	"github.com/vitakras/libinput-gestures/pkg/libinput"
)

type FakeProcessor struct {
	ProcessStub        func(debugEvent *libinput.DebugEvent) error
	processMutex       sync.RWMutex
	processArgsForCall []struct {
		debugEvent *libinput.DebugEvent
	}
	processReturns struct {
		result1 error
	}
	processReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProcessor) Process(debugEvent *libinput.DebugEvent) error {
	fake.processMutex.Lock()
	ret, specificReturn := fake.processReturnsOnCall[len(fake.processArgsForCall)]
	fake.processArgsForCall = append(fake.processArgsForCall, struct {
		debugEvent *libinput.DebugEvent
	}{debugEvent})
	fake.recordInvocation("Process", []interface{}{debugEvent})
	fake.processMutex.Unlock()
	if fake.ProcessStub != nil {
		return fake.ProcessStub(debugEvent)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.processReturns.result1
}

func (fake *FakeProcessor) ProcessCallCount() int {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	return len(fake.processArgsForCall)
}

func (fake *FakeProcessor) ProcessArgsForCall(i int) *libinput.DebugEvent {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	return fake.processArgsForCall[i].debugEvent
}

func (fake *FakeProcessor) ProcessReturns(result1 error) {
	fake.ProcessStub = nil
	fake.processReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProcessor) ProcessReturnsOnCall(i int, result1 error) {
	fake.ProcessStub = nil
	if fake.processReturnsOnCall == nil {
		fake.processReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.processReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProcessor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProcessor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ app.Processor = new(FakeProcessor)
